# Generated by Django 3.0.4 on 2020-11-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='specialisation',
            field=models.CharField(choices=[('GENERALMEDICINE', 'GENERALMEDICINE'), ('PAEDIATRICS', 'PAEDIATRICS')], default='GENERALMEDICINE', max_length=20),
        ),
    ]
