# Generated by Django 3.0.4 on 2020-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_doctors_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='specialisation',
            field=models.CharField(choices=[('GENERALMEDICINE', 'GENERALMEDICINE'), ('PAEDIATRICS', 'PAEDIATRICS'), ('ONCOLOGY', 'ONCOLOGY'), ('CARDIOLOGIST', 'CARDIOLOGIST'), ('DERMATOLOGIST', 'DERMATOLOGIST')], default='GENERALMEDICINE', max_length=20),
        ),
    ]
