# Generated by Django 3.0.4 on 2020-11-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201115_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='doctor',
            new_name='Name',
        ),
    ]
