# Generated by Django 3.0.4 on 2020-11-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201115_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='address',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone no.'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
