# Generated by Django 3.0.4 on 2020-11-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_userprofileinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
