# Generated by Django 3.0.4 on 2020-11-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20201118_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='day',
            field=models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'Three'), ('4', 'Four')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
